### PR TITLE
Formated some codes and removed some non-blocking assignments from combinational always blocks

### PR DESCRIPTION
**Pull request by AhsanAliUet**
Hello. I saw your codes for pipeline 5 stage RISCV32I. It was a good one. I tried to format your codes to increase their read ability. Also, I removed some non-blocking (<=) assignments from combinational always blocks which contain blocking (=) assignments. 

Looking forward for your positive response for merger of the pull request.

Thanks!

### CODE REVIEW

**Comment by EmJunaid** [comment]
Thanks Ahsan for your efforts. I will soon review the changes and will update you. 
Just a quick question, did you run any test/simulation after doing these changes?

**Comment by AhsanAliUet** [comment]
Yes I run some quick simulations. But I suggest you to verify it once more.
So that this processor is a good example for others.

**Comment by AhsanAliUet** [comment]
Yes I run some quick simulations. But I suggest you to verify it once more. So that this processor is a good example for others. 

After that, will add some peripheral support to this also.

**Comment by EmJunaid** [comment]
Yeah sure, I'll verify from my side as well.
Regarding peripheral support, I will appreciate the initiative but before you start working on that let's have a meeting to discuss it to make the process more efficient because I also have some ideas related to peripheral supports.

**Comment by AhsanAliUet** [comment]
Sure. We can have a meeting. Please verify and let me know.

**Comment by AhsanAliUet** [comment]
Hello. I found some issue during simulation. ALU is not giving its output while its inputs are there. Everything else is good, I think.

**Comment by EmJunaid** [comment]
Ok, I'll take a look at it.

**Review by EmJunaid — APPROVED** [review]

**Review by EmJunaid — APPROVED** [review]

**Review by EmJunaid — APPROVED** [review]

**Review by EmJunaid — APPROVED** [review]

**Comment by EmJunaid** [comment]
What/Why you have added x0 logic in data memory module? shouldn't it has to be in register file ?

**Comment by AhsanAliUet** [comment]
Sorry, actually it should be in reg file. It was added accidentally. Thanks for clarification

**Review by EmJunaid — COMMENTED** [review]
We cannot use assign statement for a reg data type. Either use always block for reg or maybe change reg data type to a wire.
Talking about PCPlus4.v .

**Comment by EmJunaid** [comment]
Have you added the x0 logic to the register file? If not then kindly add that and I'll merge your PR, rest of the changes seems good.

**Comment by AhsanAliUet** [comment]
What do you mean by x0 logic exactly? Can you please tell?

**Comment by EmJunaid** [comment]
Let's consider this assembly code:
addi x0,x0,10 (In my reg file implementation 10 will be written in x0, but this should not happen)
addi x1,x0,10 (Now x0 will provide value of 10 instead of 0 which is wrong).
I know maybe no one uses x0 as rd in the first place but we have to make sure from our side that x0 always provide 0. 
So you need to put some logic/check in register file to avoid this behaviour.

**Comment by AhsanAliUet** [comment]
Right. You mean avoid writing to x0, right?

**Comment by AhsanAliUet** [comment]
I created another pull request accidentally. Sorry.

**Comment by EmJunaid** [comment]
> Right. You mean avoid writing to x0, right?

yes

**Comment by AhsanAliUet** [comment]
Right. I added that logic too. Now Should I start testing it using self checking test benches?

**Comment by EmJunaid** [comment]
Yeah, go for it and I'll suggest to test one instruction type at one type, like first just check different kind of I-type instructions, the s-type and so on and then maybe you can mix multiple or all of them. 
I'll also check on my side as well.

**Comment by AhsanAliUet** [comment]
Fine.

**Comment by EmJunaid** [comment]
Did you push the changes you made for x0 logic?

**Comment by AhsanAliUet** [comment]
Yes. It is in Dev pull request which was created accidentally.

**Comment by EmJunaid** [comment]
ok

**Pull request merged**
