### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by AhsanAliUet**

### CODE REVIEW

**Review by EmJunaid — COMMENTED** [review]
what is this logic? kindly explain it.
(RegWriteW && (|RdW))

**Comment by AhsanAliUet** [comment]
It means that when address is non-zero (check by OR, bit by bit) and there
is a register write signal asserted, then write on register file. Else not.

**Comment by EmJunaid** [comment]
How you can take OR on a single signal? Can't OR required two signals(vlaues)?

**Comment by EmJunaid** [comment]
Can't you just do something like:
(RegWriteW && (RdW!=5'd0))

**Comment by AhsanAliUet** [comment]
It is applicable. It is bit by bit OR?

**Comment by AhsanAliUet** [comment]
The last expression you sent will make a comparator of 5 bit in hardware
and which was doing bit by bit or will just make OR gate. Comparator takes
substantial amount of logic while OR does not. Therefore, I used bit by bit
OR to avoid writing at x0

**Pull request merged**
